// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQdhOzmAu2imL9u0uDnQhjg6YxbMq-2G8',
    appId: '1:1011006209917:web:b0fc4ca5a3367d48355614',
    messagingSenderId: '1011006209917',
    projectId: 'muambao',
    authDomain: 'muambao.firebaseapp.com',
    storageBucket: 'muambao.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy1pxG33vlfaOX83JSUzkuqydgSPbuW4M',
    appId: '1:1011006209917:android:8894e23374cd40ec355614',
    messagingSenderId: '1011006209917',
    projectId: 'muambao',
    storageBucket: 'muambao.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQdhOzmAu2imL9u0uDnQhjg6YxbMq-2G8',
    appId: '1:1011006209917:web:928a59919cad103c355614',
    messagingSenderId: '1011006209917',
    projectId: 'muambao',
    authDomain: 'muambao.firebaseapp.com',
    storageBucket: 'muambao.appspot.com',
  );
}
